app = 'app-patient-sound-2595'
primary_region = 'nrt'

[build]

[env]
  NODE_ENV = 'production'
  PORT = '3000'
  TZ = 'Asia/Seoul'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1

[deploy]
  strategy = 'immediate'
  max_unavailable = 1

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
